# Generated by Django 2.2.4 on 2025-07-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saned_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456789, max_length=255),
            preserve_default=False,
        ),
    ]
