# Generated by Django 2.2.4 on 2025-07-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saned_app', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=255),
        ),
    ]
