# Generated by Django 2.2.4 on 2025-07-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saned_app', '0003_auto_20250710_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saned_app.NGOProfile'),
        ),
    ]
